#!/usr/bin/env bash
#
# Simple script for use with @semantic-release/exec
#
# (OPTIONAL) If you want any files modified by this process
# checked back in to the repository prior to release,
# add those files to the list of assets for the
# @semantic-release/git plugin.
#
# shellcheck disable=SC2154

NEXT_VERSION=${1-}
if [[ -z ${NEXT_VERSION} ]]; then
  echo "Version missing. expected version as first argument."
  exit 1
fi

PKG="jexy-dummy"

# make sure there's no v prefix
TRIMMED_VERSION="${NEXT_VERSION}"
if [[ ${TRIMMED_VERSION:0:1} == "v" ]]; then
  TRIMMED_VERSION=${TRIMMED_VERSION:1}
fi

echo "${TRIMMED_VERSION}" >${GITHUB_WORKSPACE:-.}/.next-version

make build
